### PR TITLE
Upgrade and Deploy for 3.7

### PR DESCRIPTION
**Pull request by jpadilla**
- [X] Update all dependencies
- [X] Add Core API schema endpoint
- [X] Add interactive api docs endpoint
- [x] Update fixtures
- [x] Management command to reset data every x minutes via cron on Heroku
- [x] Setup cron on Heroku
- [x] Setup automatic deploys

Also, found some things to fix/improve in some of the tutorial sections(will open PR soon).

### CODE REVIEW

**Comment by carltongibson** [comment]
Hey @jpadilla. This is looking great. 

You should have Heroku access ≈today. After that, if there's anything else you need, ping me. 

I'm lining up DRF v3.7.4 for before the holiday break.https://github.com/encode/django-rest-framework/pull/5650 That's a good target for this as well. 

Thanks for your effort! You rock! 🎸🤘🏽💃🏼🎉

**Comment by tomchristie** [comment]
@jpadilla Added you as a collaborator to the Heroku project.

**Comment by jpadilla** [comment]
@carltongibson great, I'll make sure to tackle the rest of the things left before then.

@tomchristie perf, thanks! I don't have enough permissions on this org, so I'll also need you to connect the app the repo, at the bottom [here](https://dashboard.heroku.com/apps/restframework/deploy/github).

**Comment by jpadilla** [comment]
So I think this is done! Before merging I'd love to finish setting up automatic deploys, but that will require @tomchristie [connecting](https://dashboard.heroku.com/apps/restframework/deploy/github) the app to the repo as it seems I don't have enough permissions on the encode org to do so.

Once that's done, and this PR is approved, I'll merge, make sure deploy is working and setup the cleanup cron.

**Comment by tomchristie** [comment]
@jpadilla Okay, I [think that's done](https://dashboard.heroku.com/pipelines/9d993907-ce6d-4005-920f-c7448a3623df). Want to have a look, and then try merging this?

**Comment by jpadilla** [comment]
@tomchristie I see the new pipeline, but I'm not seeing it connected to GitHub yet. Are you?

screen shot 2017-12-18 at 7 39 25 pm

**Comment by jpadilla** [comment]
@tomchristie bumping this up, can schedule to jump in a call if you'd like.

**Comment by tomchristie** [comment]
Thanks so much @jpadilla. Should be connected now. (Sorry - not familiar with the pipeline UI.)
If that's still not it then let me know and we can hop on a call together sometime and sort it.

**Comment by jpadilla** [comment]
Almost done with this. Heroku is having some issues today so taking a bit longer than what I hoped.

**Pull request merged**
